"""add category to documents

Revision ID: 7e60b5f3ae5a
Revises: f2a4b6c8d0e1
Create Date: 2026-09-13 00:46:58.397018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e60b5f3ae5a'
down_revision: Union[str, Sequence[str], None] = 'f2a4b6c8d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'category')
    # ### end Alembic commands ###
